version: "3"

services:
  web:
    build:
      context: .
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/test_app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:11-alpine

    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  pgdata:
